-- MySQL Script generated by MySQL Workbench
-- Mon Jan 17 17:22:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_projeto_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_projeto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projeto_integrador` DEFAULT CHARACTER SET utf8 ;
USE `db_projeto_integrador` ;

-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email_usuario` VARCHAR(100) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  `foto_usuario` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_postagens` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `titulo_post` VARCHAR(255) NOT NULL,
  `texto_post` VARCHAR(1000) NOT NULL,
  `data_post` DATETIME NOT NULL,
  `imagem_post` VARCHAR(255) NULL,
  `likes_post` BIGINT NULL DEFAULT 0,
  `tema_post` ENUM('VAGAS', 'SERVICOS', 'ARTIGOS') NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_tb_postagens_tb_usuarios_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_projeto_integrador`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_publico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_publico` (
  `id_publico` INT NOT NULL AUTO_INCREMENT,
  `lgbtqiap` TINYINT NOT NULL,
  `mulheres` TINYINT NOT NULL,
  `pcds` TINYINT NOT NULL,
  `indigenas` TINYINT NOT NULL,
  `id_post` INT NOT NULL,
  PRIMARY KEY (`id_publico`),
  INDEX `fk_tb_publico_tb_postagens1_idx` (`id_post` ASC) VISIBLE,
  CONSTRAINT `fk_tb_publico_tb_postagens1`
    FOREIGN KEY (`id_post`)
    REFERENCES `db_projeto_integrador`.`tb_postagens` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
